package com.riotgames.platform.gameclient.domain
{
   public class RuneCategories extends Object
   {
      
      public static var RUNE_CATEGORY_MANA:int = 2;
      
      public static var RUNE_CATEGORY_DEFENSE:int = 5;
      
      public static var RUNE_CATEGORY_ALL:int = 0;
      
      public static var RUNE_CATEGORY_MAGIC:int = 4;
      
      public static var RUNE_CATEGORY_UNUSED:int = -1;
      
      public static var RUNE_CATEGORY_PHYSICAL_ATTACK:int = 3;
      
      public static var categoryNamesArray:Array = ["All","Health","Mana","PhysicalAttack","Magic","Defense","Utility"];
      
      public static var RUNE_CATEGORY_UTILITY:int = 6;
      
      public static var RUNE_CATEGORY_HEALTH:int = 1;
      
      public static var effectToCategoryMap:Array = [RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_HEALTH,RUNE_CATEGORY_HEALTH,RUNE_CATEGORY_MANA,RUNE_CATEGORY_MANA,RUNE_CATEGORY_HEALTH,RUNE_CATEGORY_MANA,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_HEALTH,RUNE_CATEGORY_HEALTH,RUNE_CATEGORY_HEALTH,RUNE_CATEGORY_MANA,RUNE_CATEGORY_MANA,RUNE_CATEGORY_MANA,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_MAGIC,RUNE_CATEGORY_MAGIC,RUNE_CATEGORY_MAGIC,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_PHYSICAL_ATTACK,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_DEFENSE,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_UTILITY,RUNE_CATEGORY_UNUSED,RUNE_CATEGORY_MAGIC,RUNE_CATEGORY_MAGIC,RUNE_CATEGORY_MAGIC,RUNE_CATEGORY_MAGIC];
      
      public function RuneCategories()
      {
         super();
      }
   }
}
